### ISSUE TITLE
db:seed does not work

### ISSUE THREAD

**Issue by joaocsilva** [malhal/Laravel-CreatedBy#2]
Hi,
Does not have possibility to seed database?
I suggest one simple trick to force auth by first user, what you think about.

```
# malhal/laravel-createdby/src/CreatedBy.php line 52
if (!$user && App::runningInConsole()) {
    Auth::loginUsingId(1);
    $user = Auth::user();
}
```

**Comment by malhal** [comment]
Hi thanks for using the project! You can set the user directly like this:

`$model->setAttribute($model->getCreatedByForeignKeyName(), $user->getKey());`

or

`$model->setAttribute($model->getCreatedByForeignKeyName(), 1);`

or maybe just:

`$model->created_by_id = 1;`

If this attribute is set before the save then the creator won't be replaced. You might want to also set the updatedBy in same way.

**Comment by joaocsilva** [comment]
Hi thanks for your reply.

My problem is when you runnig `php artisan db:seed` that does not exist user to use, so `$user->getKey()` does not exists.

But yes, second solution work fine, but if you want save time to user, you can add this lines to project, can I open one branch for that if you want.

**Comment by malhal** [comment]
just seed the user first and keep the $user variable to use

**Comment by malhal** [comment]
Or if this is a different file just load the user with user = User::find(1);

**Comment by malhal** [comment]
Overall I think logging in the user with Auth in your seed file is probably the way to go.
